language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t wilsonwaterman/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true wilsonwaterman/frontend npm run test