language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t wilsonwaterman/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true wilsonwaterman/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-frontend"
  env: "DockerReactFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-649148530717"
  bucket_path: "docker-react-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY